# Generated by Django 5.2.5 on 2025-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin1',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
