# Generated by Django 4.2.7 on 2025-08-18 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Enter your first name (max 50 characters)', max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Enter your last name (max 50 characters)', max_length=50, null=True, verbose_name='Last Name')),
                ('contact_number', models.CharField(blank=True, help_text='Enter a valid contact number (max 15 digits)', max_length=15, null=True, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, help_text='Enter your complete address', null=True, verbose_name='Address')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Select your gender', max_length=10, null=True, verbose_name='Gender')),
                ('city', models.CharField(blank=True, help_text='Enter your city name (max 50 characters)', max_length=50, null=True, verbose_name='City')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Select your blood group', max_length=5, null=True, verbose_name='Blood Group')),
                ('role', models.CharField(blank=True, choices=[('donor', 'Donor'), ('needer', 'Needer')], help_text='Select your role - Donor or Needer', max_length=10, null=True, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
