# Generated by Django 5.2.5 on 2025-08-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_admin1_password_admin1_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
