# Generated by Django 4.2.7 on 2025-08-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Required blood group', max_length=5, verbose_name='Blood Group')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('user_accepted', 'User Accepted'), ('donor_accepted', 'Donor Accepted'), ('both_accepted', 'Both Accepted'), ('user_declined', 'User Declined'), ('donor_declined', 'Donor Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the donation request', max_length=20, verbose_name='Status')),
                ('user_response', models.BooleanField(blank=True, help_text='True if user accepts, False if declines, None if no response', null=True, verbose_name='User Response')),
                ('donor_response', models.BooleanField(blank=True, help_text='True if donor accepts, False if declines, None if no response', null=True, verbose_name='Donor Response')),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Urgency level of the blood requirement', max_length=10, verbose_name='Urgency Level')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this request expires', null=True, verbose_name='Expires At')),
                ('donor', models.ForeignKey(help_text='Donor who can provide blood', on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who needs blood', on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Request',
                'verbose_name_plural': 'Donation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_status', models.CharField(choices=[('initiated', 'Initiated'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], default='initiated', help_text='Status of the phone call', max_length=15, verbose_name='Call Status')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Call duration in seconds', null=True, verbose_name='Duration (seconds)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the call ended', null=True, verbose_name='Ended At')),
                ('notes', models.TextField(blank=True, help_text='Notes about the call', null=True, verbose_name='Call Notes')),
                ('caller', models.ForeignKey(help_text='User who made the call', on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('donation_request', models.ForeignKey(help_text='Related donation request', on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='donation.donationrequest')),
                ('receiver', models.ForeignKey(help_text='User who received the call', on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('alert', 'Alert'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('notification', 'Notification')], default='notification', help_text='Type of message', max_length=15, verbose_name='Message Type')),
                ('subject', models.CharField(help_text='Message subject', max_length=200, verbose_name='Subject')),
                ('content', models.TextField(help_text='Message content', verbose_name='Content')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', help_text='Message delivery status', max_length=15, verbose_name='Delivery Status')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS delivery', max_length=15, null=True, verbose_name='Phone Number')),
                ('is_sms', models.BooleanField(default=False, help_text='Whether this message should be sent as SMS', verbose_name='Is SMS')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the message was sent', null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered', null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was read', null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('donation_request', models.ForeignKey(blank=True, help_text='Related donation request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='donation.donationrequest')),
                ('recipient', models.ForeignKey(help_text='User who received the message', on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'delivery_status'], name='donation_me_recipie_45f660_idx'), models.Index(fields=['donation_request', 'message_type'], name='donation_me_donatio_2aacf3_idx'), models.Index(fields=['sender', 'created_at'], name='donation_me_sender__7a0c04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['requester', 'status'], name='donation_do_request_d797e8_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['donor', 'status'], name='donation_do_donor_i_5166ee_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['blood_group', 'status'], name='donation_do_blood_g_bab1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['donation_request', 'call_status'], name='donation_ca_donatio_bc4f05_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['caller', 'started_at'], name='donation_ca_caller__6e2556_idx'),
        ),
    ]
