# Generated by Django 4.2.7 on 2025-08-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationrequest_calllog_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether email has been sent', verbose_name='Email Sent'),
        ),
        migrations.AddField(
            model_name='message',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the email was sent', null=True, verbose_name='Email Sent At'),
        ),
        migrations.AddField(
            model_name='message',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Whether SMS has been sent', verbose_name='SMS Sent'),
        ),
        migrations.AddField(
            model_name='message',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the SMS was sent', null=True, verbose_name='SMS Sent At'),
        ),
    ]
