# Generated by Django 5.2.5 on 2025-08-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_signup1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup1',
            new_name='Registration',
        ),
    ]
