# Generated by Django 5.2.5 on 2025-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_rename_signup1_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone_number',
        ),
    ]
