# Generated by Django 4.2.7 on 2025-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_message_email_sent_message_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Sheikhupura', 'Sheikhupura'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Faisalabad', 'Faisalabad')], help_text='Select your city', max_length=50, null=True, verbose_name='City'),
        ),
    ]
