# Generated by Django 5.2.5 on 2025-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_rename_first_name_registration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
