# Generated by Django 5.2.5 on 2025-08-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_registration_is_verified_registration_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.AddField(
            model_name='registration',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
    ]
