# Generated by Django 4.2.7 on 2025-08-21 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_admin_admin_unique_admin_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='both_confirmed',
            field=models.BooleanField(default=False, help_text='Whether both parties have confirmed the call completion', verbose_name='Both Confirmed'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='caller_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the caller confirmed the call completion', verbose_name='Caller Confirmed'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When both parties confirmed the call', null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='receiver_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the receiver confirmed the call completion', verbose_name='Receiver Confirmed'),
        ),
        migrations.CreateModel(
            name='MonthlyDonationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month being tracked (YYYY-MM-01 format)', verbose_name='Month')),
                ('completed_calls_count', models.PositiveIntegerField(default=0, help_text='Number of confirmed calls completed this month', verbose_name='Completed Calls Count')),
                ('monthly_goal_completed', models.BooleanField(default=False, help_text='Whether the monthly goal of 3 calls has been completed', verbose_name='Monthly Goal Completed')),
                ('goal_completed_at', models.DateTimeField(blank=True, help_text='When the monthly goal was completed', null=True, verbose_name='Goal Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='User whose monthly donations are being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Donation Tracker',
                'verbose_name_plural': 'Monthly Donation Trackers',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', 'month'], name='donation_mo_user_id_22b303_idx'), models.Index(fields=['monthly_goal_completed'], name='donation_mo_monthly_7a7484_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
