# Generated by Django 4.2.7 on 2025-08-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_calllog_both_confirmed_calllog_caller_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProfiles',
            fields=[
            ],
            options={
                'verbose_name': 'Blocked Profile',
                'verbose_name_plural': 'Blocked Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('donation.monthlydonationtracker',),
        ),
    ]
