# Generated by Django 5.2.5 on 2025-08-24 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_blockedprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='donation_request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Call Log', 'verbose_name_plural': 'Call Logs'},
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='donation_ca_donatio_bc4f05_idx',
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='donation_ca_caller__6e2556_idx',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='donation_request',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='both_confirmed',
            field=models.BooleanField(default=False, help_text='Whether both parties confirmed the call', verbose_name='Both Confirmed'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('answered', 'Answered'), ('completed', 'Completed'), ('missed', 'Missed'), ('declined', 'Declined')], default='initiated', help_text='Current status of the call', max_length=20, verbose_name='Call Status'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller',
            field=models.ForeignKey(help_text='User who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller_confirmed',
            field=models.BooleanField(default=False, help_text='Whether caller confirmed the call completion', verbose_name='Caller Confirmed'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the call in seconds', null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='receiver_confirmed',
            field=models.BooleanField(default=False, help_text='Whether receiver confirmed the call completion', verbose_name='Receiver Confirmed'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['caller', 'call_status'], name='donation_ca_caller__7b8ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['receiver', 'call_status'], name='donation_ca_receive_466c40_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['created_at'], name='donation_ca_created_b32a0a_idx'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
