# Generated by Django 4.2.7 on 2025-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_remove_message_donation_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='donor_email_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes - Agreed to Donate'), ('no', 'No - Declined to Donate')], default='pending', help_text='Donor response from email confirmation', max_length=10, verbose_name='Donor Email Response'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='email_response_at',
            field=models.DateTimeField(blank=True, help_text='When donor responded via email', null=True, verbose_name='Email Response At'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether confirmation email was sent to donor', verbose_name='Email Sent'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the confirmation email was sent', null=True, verbose_name='Email Sent At'),
        ),
    ]
