# Generated by Django 5.2.5 on 2025-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_calllog_donor_email_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the donation request', null=True, verbose_name='Notes'),
        ),
    ]
