# Generated by Django 5.2.5 on 2025-09-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_donationrequest_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donor_response',
            field=models.BooleanField(blank=True, null=True, verbose_name='Donor Response'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('user_accepted', 'User Accepted'), ('donor_accepted', 'Donor Accepted'), ('both_accepted', 'Both Accepted'), ('user_declined', 'User Declined'), ('donor_declined', 'Donor Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='user_response',
            field=models.BooleanField(blank=True, null=True, verbose_name='User Response'),
        ),
        migrations.AlterField(
            model_name='monthlydonationtracker',
            name='completed_calls_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Completed Calls Count'),
        ),
        migrations.AlterField(
            model_name='monthlydonationtracker',
            name='goal_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Goal Completed At'),
        ),
        migrations.AlterField(
            model_name='monthlydonationtracker',
            name='month',
            field=models.DateField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlydonationtracker',
            name='monthly_goal_completed',
            field=models.BooleanField(default=False, verbose_name='Monthly Goal Completed'),
        ),
        migrations.AlterField(
            model_name='monthlydonationtracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trackers', to=settings.AUTH_USER_MODEL),
        ),
    ]
